import React, { useRef, useMemo } from 'react';
import { View, Text, TouchableOpacity, StyleSheet, ScrollView, Alert } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { captureRef } from 'react-native-view-shot';
import * as Sharing from 'expo-sharing';
import * as Haptics from 'expo-haptics';
import { MOODS } from '../constants/moods';

export default function ShareScreen ({ logs, todayMood, todayNote }) {
  const cardRef = useRef();

  const shareText = useMemo(() => {
    if (todayNote) return `"${todayNote}"`;
    if (todayMood) {
      const mood = MOODS.find(m => m.id === todayMood);
      return mood ? mood.quote : "这个月，我诚实地面对了自己。";
    }
    return "这个月，我诚实地面对了自己。";
  }, [todayNote, todayMood]);

  const getShareGradient = () => {
    if (todayMood) {
      const mood = MOODS.find(m => m.id === todayMood);
      return mood ? mood.gradient : ['#6366f1', '#a855f7'];
    }
    return ['#6366f1', '#a855f7'];
  };

  const handleShare = async () => {
    try {
      if (Platform.OS === 'ios') Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      const uri = await captureRef(cardRef, { format: 'png', quality: 1 });
      await Sharing.shareAsync(uri);
    } catch (e) {
      Alert.alert("抱歉", "生成分享图片失败了");
    }
  };

  return (
    <ScrollView contentContainerStyle={styles.scrollPage}>
      <Text style={styles.pageTitle}>分享卡片</Text>
      <View style={styles.cardContainer} ref={cardRef} collapsable={false}>
        <LinearGradient
          colors={getShareGradient()}
          style={styles.card}
          start={{ x: 0, y: 0 }}
          end={{ x: 1, y: 1 }}
        >
          <View style={styles.cardHeader}>
            <Text style={styles.appName}>MOODFLOW</Text>
            <View style={styles.cardIcon}>
              <Ionicons name="sunny" size={20} color="#FDE047" />
            </View>
          </View>
          <View style={{ flex: 1, justifyContent: 'center' }}>
            <Text style={styles.cardMainText} numberOfLines={3}>
              {shareText}
            </Text>
          </View>
          <View style={styles.cardStatsRow}>
            <Text style={styles.cardStatText}>✨ 已记录 {Object.keys(logs).length} 天</Text>
            <Text style={styles.cardStatText}>📅 {new Date().toLocaleDateString()}</Text>
          </View>
          <View style={styles.dotsRow}>
            {[...Array(5)].map((_, i) => (
              <View key={i} style={[styles.dot, i < 3 ? { backgroundColor: 'rgba(255,255,255,0.6)' } : {}]} />
            ))}
          </View>
          <View style={styles.cardFooter}>
            <Text style={styles.cardFooterText}>Generated by MoodFlow App</Text>
          </View>
        </LinearGradient>
      </View>
      <TouchableOpacity style={styles.actionButton} onPress={handleShare}>
        <Ionicons name="share-outline" size={20} color="white" />
        <Text style={styles.actionButtonText}>分享给朋友</Text>
      </TouchableOpacity>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  scrollPage: { flexGrow: 1, padding: 24 },
  pageTitle: { fontSize: 22, fontWeight: 'bold', color: '#111827', marginBottom: 20 },
  cardContainer: { width: '100%', aspectRatio: 0.8, marginBottom: 30, shadowColor: '#6366f1', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.3, shadowRadius: 20, elevation: 10 },
  card: { flex: 1, borderRadius: 24, padding: 24, justifyContent: 'space-between' },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  appName: { color: 'rgba(255,255,255,0.8)', fontSize: 12, letterSpacing: 1, fontWeight: '700' },
  cardIcon: { backgroundColor: 'rgba(255,255,255,0.2)', padding: 8, borderRadius: 8 },
  cardMainText: { fontSize: 28, color: 'white', fontWeight: 'bold', lineHeight: 36 },
  cardStatsRow: { flexDirection: 'row', gap: 12 },
  cardStatText: { color: 'rgba(255,255,255,0.9)', fontSize: 14, fontWeight: '500' },
  dotsRow: { flexDirection: 'row', gap: 8 },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: 'rgba(255,255,255,0.3)' },
  cardFooter: { borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.2)', paddingTop: 16 },
  cardFooterText: { color: 'rgba(255,255,255,0.6)', fontSize: 10 },
  actionButton: { flexDirection: 'row', backgroundColor: '#111827', paddingVertical: 16, paddingHorizontal: 32, borderRadius: 12, alignItems: 'center', gap: 8 },
  actionButtonText: { color: 'white', fontSize: 16, fontWeight: '600' },
});
